/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mule_api_jni_Bridge */

#ifndef _Included_org_mule_api_jni_Bridge
#define _Included_org_mule_api_jni_Bridge
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     org_mule_api_jni_Bridge
	* Method:    init
	* Signature: (Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_org_mule_api_jni_Bridge_init
		(JNIEnv *, jobject, jobject);

	/*
        * Class:     org_mule_api_jni_Bridge
        * Method:    invokeNetMethod
        * Signature: (Ljava/lang/String;[B)Ljava/lang/String;
        */
       JNIEXPORT jstring JNICALL Java_org_mule_api_jni_Bridge_invokeNetMethod
         (JNIEnv *, jobject, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
